/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import java.sql.ResultSet;
import java.sql.Connection;
import DBConnect.DBConnect;
import form.NewJFrame;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.SinhVien;
/**
 *
 * @author minhtung
 */
public class SignIn extends javax.swing.JFrame {
     Connection conn=null;
       ResultSet rs=null, rsAdmin=null;
         PreparedStatement pst=null, pstAdmin=null;
     /**
      * Creates new form SignIn
      * @throws java.sql.SQLException
      */
     public SignIn() throws SQLException {
          initComponents();
           this.setLocationRelativeTo(null);
          conn=DBConnect.getConnection();
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jTextField1 = new javax.swing.JTextField();
          jPanel1 = new javax.swing.JPanel();
          jpassword = new javax.swing.JPasswordField();
          jButton1 = new javax.swing.JButton();
          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          jusername = new javax.swing.JTextField();
          jSeparator1 = new javax.swing.JSeparator();
          jSeparator2 = new javax.swing.JSeparator();

          jTextField1.setText("jTextField1");

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
          setLocationByPlatform(true);
          setUndecorated(true);

          jPanel1.setBackground(new java.awt.Color(36, 47, 65));

          jpassword.setBackground(new java.awt.Color(36, 47, 65));
          jpassword.setForeground(new java.awt.Color(255, 255, 255));
          jpassword.setText("enter your password");
          jpassword.setBorder(null);
          jpassword.setDisabledTextColor(new java.awt.Color(255, 255, 255));
          jpassword.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jpasswordMouseClicked(evt);
               }
          });

          jButton1.setBackground(new java.awt.Color(97, 212, 195));
          jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
          jButton1.setForeground(new java.awt.Color(255, 255, 255));
          jButton1.setText("Đăng nhập");
          jButton1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
               }
          });

          jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          jLabel1.setForeground(new java.awt.Color(255, 255, 255));
          jLabel1.setText("FullName");

          jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
          jLabel2.setForeground(new java.awt.Color(255, 255, 255));
          jLabel2.setText("Password");

          jusername.setBackground(new java.awt.Color(36, 47, 65));
          jusername.setForeground(new java.awt.Color(255, 255, 255));
          jusername.setText("Enter your username");
          jusername.setBorder(null);
          jusername.setDisabledTextColor(new java.awt.Color(255, 255, 255));
          jusername.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jusernameMouseClicked(evt);
               }
          });

          jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

          jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGap(73, 73, 73)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jusername, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGap(135, 135, 135)
                              .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(104, Short.MAX_VALUE))
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jusername, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                    .addComponent(jpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(72, 72, 72))
          );

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void jusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jusernameMouseClicked
          // TODO add your handling code here:
          jusername.setText("");
     }//GEN-LAST:event_jusernameMouseClicked

     private void jpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpasswordMouseClicked
          // TODO add your handling code here:
          jpassword.setText("");
     }//GEN-LAST:event_jpasswordMouseClicked

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          // TODO add your handling code here:
          String username =jusername.getText();
          String pass=String.valueOf(jpassword.getPassword()).trim();
        
          try {
                 String sql ="select * from account where username=? and password=?";
               pst=conn.prepareCall(sql);
               pst.setString(1, username);
               pst.setString(2, pass);
               rs=pst.executeQuery();
               
               
               if(rs.next()){
                    int id =rs.getInt("idAccount");
                    int role =rs.getInt("role");
                    if(role==0){
                        SinhVien sv=setdata(id);
                         NewJFrame frameSV=new NewJFrame(sv);
                         frameSV.setVisible(true);
                         this.setVisible(false);
                         this.dispose();
                    }else if(role ==1){
                         NewJFrame frame=new NewJFrame();
                         frame.setVisible(true);
                         this.setVisible(false);
                         this.dispose();
                    }
               }else{
                    System.out.println("that bai");
               }
               
          } catch (SQLException ex) {
               Logger.getLogger(SignIn.class.getName()).log(Level.SEVERE, null, ex);
          }
          
          
          
     }//GEN-LAST:event_jButton1ActionPerformed
     public SinhVien setdata(int id) throws SQLException{
          SinhVien sv=new SinhVien();
          String sql="select * from SinhVien where idAccount='"+id+"' ";
          pst=conn.prepareCall(sql);
          rs=pst.executeQuery();
          while(rs.next()){
               sv.setIdSV(rs.getInt("idSV"));
               sv.setIdAccount(rs.getInt("idAccount"));
               sv.setName(rs.getString("name"));
               sv.setChuyenNganh(rs.getString("ChuyenNganh"));
               sv.setLopHoc(rs.getString("LopHoc"));
               sv.setKhoaHoc(rs.getInt("KhoaHoc"));
               sv.setStatus(rs.getInt("status"));    
          }
          return sv;
     }
     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    try {
                         new SignIn().setVisible(true);
                    } catch (SQLException ex) {
                         Logger.getLogger(SignIn.class.getName()).log(Level.SEVERE, null, ex);
                    }
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton jButton1;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JSeparator jSeparator1;
     private javax.swing.JSeparator jSeparator2;
     private javax.swing.JTextField jTextField1;
     private javax.swing.JPasswordField jpassword;
     private javax.swing.JTextField jusername;
     // End of variables declaration//GEN-END:variables
}
