/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.sql.SQLException;
import java.sql.Statement;

import model.HocPhi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author minhtung
 */
public class edit extends javax.swing.JFrame {
     Connection con=null;
     /**
      * Creates new form edit
      */
     public edit() {
          initComponents();
     }
     public edit(HocPhi hp) throws SQLException{
          initComponents();
          con=DBConnect.DBConnect.getConnection();
//          jidsv.setVisible(false);
          jidsv.setText(String.valueOf(hp.getIdSV()));
          jkhoa.setText(String.valueOf(hp.getKhoaHoc()));
          jnamhoc.setText(hp.getNamHoc());
          jtienphainop.setText(String.valueOf(hp.getTienPhaiNop()));
          jtiendanop.setText(String.valueOf(hp.getTienDaNop()));
          
     }


     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jButton1 = new javax.swing.JButton();
          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          jkhoa = new javax.swing.JTextField();
          jnamhoc = new javax.swing.JTextField();
          jtienphainop = new javax.swing.JTextField();
          jtiendanop = new javax.swing.JTextField();
          jidsv = new javax.swing.JTextField();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          jButton1.setText("Save");
          jButton1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
               }
          });

          jLabel1.setText("Khóa");

          jLabel2.setText("Năm Học");

          jLabel3.setText("Tiền Phải Nộp");

          jLabel4.setText("Tiền đã Nộp");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(95, 95, 95)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(67, 67, 67)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jtiendanop, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jtienphainop, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jnamhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                         .addGroup(layout.createSequentialGroup()
                              .addGap(38, 38, 38)
                              .addComponent(jidsv, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(83, 83, 83)
                              .addComponent(jButton1)))
                    .addContainerGap(42, Short.MAX_VALUE))
          );

          layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

          layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jkhoa, jnamhoc, jtiendanop, jtienphainop});

          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap(21, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel2)
                         .addComponent(jnamhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel3)
                         .addComponent(jtienphainop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel4)
                         .addComponent(jtiendanop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(53, 53, 53)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addComponent(jButton1)
                         .addComponent(jidsv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(48, 48, 48))
          );

          layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

          layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jkhoa, jnamhoc, jtiendanop, jtienphainop});

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          // TODO add your handling code here:
          int id=Integer.parseInt(jidsv.getText());
          int  khoa=Integer.parseInt(jkhoa.getText());
          String namhoc= jnamhoc.getText();
          int tienphainop=Integer.parseInt(jtienphainop.getText());
          int tiendanop=Integer.parseInt(jtiendanop.getText());
          int check=0;
          if(tienphainop-tiendanop==0){
               check=1;
          }
          String sql="update NopHocPhi set  khoa='"+khoa+"',NamHoc='"+namhoc+"',TienPhaiNop='"+tienphainop+"',TienDaNop='"+tiendanop+"',status='"+check+"' where idSV='"+id+"' and NamHoc='"+namhoc+"' ";
          executeQuery(sql);
          checkStatus(id, namhoc);
          this.setVisible(false);
          this.dispose();
     }//GEN-LAST:event_jButton1ActionPerformed
       public void checkStatus(int id, String namhoc) {
          try {
               int check = 1;
               String sql = "select * from NopHocPhi where idSV='" + id + "'  ";
               PreparedStatement ps = con.prepareCall(sql);
               ResultSet rs = ps.executeQuery();
               while (rs.next()) {

                    if (rs.getInt("status") == 0) {
                         check = 0;
                    }
               }
        
                    String sql1 = "update SinhVien set  status='" + check + "'where idSV='" + id + "' ";
                    executeQuery(sql1);
               
          } catch (SQLException e) {
               e.printStackTrace();
          }
     }
     public void executeQuery(String query) {
          Statement st;
          try {
               st = con.createStatement();
               st.executeUpdate(query);
              
          } catch (SQLException ex) {
               ex.printStackTrace();
          }
     }
     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(() -> {
               new edit().setVisible(true);
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton jButton1;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JTextField jidsv;
     private javax.swing.JTextField jkhoa;
     private javax.swing.JTextField jnamhoc;
     private javax.swing.JTextField jtiendanop;
     private javax.swing.JTextField jtienphainop;
     // End of variables declaration//GEN-END:variables
}
