/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.SinhVien;
import Controller.controller;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import login.SignIn;
import model.HocPhi;
import model.account;

import raven.cell.TableActionCellEditor;
import raven.cell.TableActionCellRender;
import raven.cell.TableActionEvent;

/**
 *
 * @author minhtung
 */
public class NewJFrame extends javax.swing.JFrame {

     Connection con;
     private TableRowSorter<TableModel> rowSoft = null;

     /**
      * Creates new form NewJFrame
      *
      * @throws java.sql.SQLException
      */
     public NewJFrame() throws SQLException {
          con = DBConnect.DBConnect.getConnection();
          initComponents();
          this.setLocationRelativeTo(null);
          jTabbedPane2.remove(jPanel4);

     }

     public NewJFrame(SinhVien sv) throws SQLException {
          initComponents();
          con = DBConnect.DBConnect.getConnection();
          this.setLocationRelativeTo(null);
          jTabbedPane2.remove(jPanel2);
          jTabbedPane2.remove(jPanel3);
          jTabbedPane2.remove(jTabbedPane1);
          jjid.setText(String.valueOf(sv.getIdSV()));
          jjname.setText(sv.getName());
          jjcn.setText(sv.getChuyenNganh());
          jjlop.setText(sv.getLopHoc());

          try {
               int sumphaidong = 0;
               int sumdadong = 0;
               String sql = "select * from NopHocPhi where idSV='" + sv.getIdSV() + "' ";
               PreparedStatement ps = con.prepareCall(sql);
               ResultSet rs = ps.executeQuery();
               while (rs.next()) {
                    sumphaidong += rs.getInt("TienPhaiNop");
                    sumdadong += rs.getInt("TienDaNop");
               }
               jLabel15.setText(String.valueOf(sumphaidong));
               jLabel17.setText(String.valueOf(sumdadong));
          } catch (SQLException e) {
               e.printStackTrace();
          }
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jLabel1 = new javax.swing.JLabel();
          jPanel1 = new javax.swing.JPanel();
          jTabbedPane2 = new javax.swing.JTabbedPane();
          jPanel2 = new javax.swing.JPanel();
          jScrollPane2 = new javax.swing.JScrollPane();
          jTable1 = new javax.swing.JTable();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          jLabel6 = new javax.swing.JLabel();
          jidSV = new javax.swing.JTextField();
          jname = new javax.swing.JTextField();
          jChuyenNganh = new javax.swing.JTextField();
          jKhoa = new javax.swing.JTextField();
          jLopHoc = new javax.swing.JTextField();
          jButton1 = new javax.swing.JButton();
          jButton2 = new javax.swing.JButton();
          jsearch = new javax.swing.JTextField();
          jidAccount = new javax.swing.JTextField();
          jPanel3 = new javax.swing.JPanel();
          jScrollPane3 = new javax.swing.JScrollPane();
          jtbHocPhi = new javax.swing.JTable();
          jTabbedPane1 = new javax.swing.JTabbedPane();
          jPanel7 = new javax.swing.JPanel();
          jScrollPane1 = new javax.swing.JScrollPane();
          jtbTaiKhoan = new javax.swing.JTable();
          jPanel8 = new javax.swing.JPanel();
          jComboBox1 = new javax.swing.JComboBox<>();
          idsv = new javax.swing.JLabel();
          ten = new javax.swing.JLabel();
          cn = new javax.swing.JLabel();
          lh = new javax.swing.JLabel();
          kh = new javax.swing.JLabel();
          jidsv = new javax.swing.JTextField();
          jten = new javax.swing.JTextField();
          jcn = new javax.swing.JTextField();
          jlh = new javax.swing.JTextField();
          jk = new javax.swing.JTextField();
          jLabel7 = new javax.swing.JLabel();
          jac = new javax.swing.JTextField();
          username = new javax.swing.JLabel();
          pass = new javax.swing.JLabel();
          jusername = new javax.swing.JTextField();
          jpass = new javax.swing.JTextField();
          jLabel10 = new javax.swing.JLabel();
          jSeparator2 = new javax.swing.JSeparator();
          namhoc = new javax.swing.JLabel();
          tien = new javax.swing.JLabel();
          jnamhoc = new javax.swing.JTextField();
          jtien = new javax.swing.JTextField();
          jButton3 = new javax.swing.JButton();
          jButton4 = new javax.swing.JButton();
          jPanel4 = new javax.swing.JPanel();
          jjname = new javax.swing.JLabel();
          jjcn = new javax.swing.JLabel();
          jjlop = new javax.swing.JLabel();
          jjid = new javax.swing.JLabel();
          jScrollPane4 = new javax.swing.JScrollPane();
          jtbPrivate = new javax.swing.JTable();
          jLabel8 = new javax.swing.JLabel();
          jLabel9 = new javax.swing.JLabel();
          jLabel11 = new javax.swing.JLabel();
          jLabel12 = new javax.swing.JLabel();
          thanhtoan = new javax.swing.JLabel();
          jLabel13 = new javax.swing.JLabel();
          jButton6 = new javax.swing.JButton();
          jLabel14 = new javax.swing.JLabel();
          jLabel15 = new javax.swing.JLabel();
          jLabel16 = new javax.swing.JLabel();
          jLabel17 = new javax.swing.JLabel();
          jPanel5 = new javax.swing.JPanel();

          jLabel1.setText("jLabel1");

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);

          jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
               public void componentShown(java.awt.event.ComponentEvent evt) {
                    jPanel2ComponentShown(evt);
               }
          });

          jTable1.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
               },
               new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
               }
          ));
          jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTable1MouseClicked(evt);
               }
          });
          jScrollPane2.setViewportView(jTable1);

          jLabel2.setText("id SV");

          jLabel3.setText("Họ và Tên");

          jLabel4.setText("Chuyên Ngành");

          jLabel5.setText("Lớp Học");

          jLabel6.setText("Khóa ");

          jButton1.setText("update");
          jButton1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
               }
          });

          jButton2.setText("delete");
          jButton2.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
          jPanel2.setLayout(jPanel2Layout);
          jPanel2Layout.setHorizontalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(112, 112, 112)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(113, 113, 113)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel2Layout.createSequentialGroup()
                              .addComponent(jidSV, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(109, 109, 109)
                              .addComponent(jsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(jPanel2Layout.createSequentialGroup()
                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jname, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jChuyenNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(143, 143, 143)
                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jButton2)
                                   .addComponent(jButton1))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jidAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
          );

          jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6});

          jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jChuyenNganh, jKhoa, jLopHoc, jidSV, jname});

          jPanel2Layout.setVerticalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jidSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel3)
                         .addComponent(jname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel2Layout.createSequentialGroup()
                              .addGap(28, 28, 28)
                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel4)
                                   .addComponent(jChuyenNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                         .addGroup(jPanel2Layout.createSequentialGroup()
                              .addGap(7, 7, 7)
                              .addComponent(jButton1)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel2Layout.createSequentialGroup()
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel6)
                                   .addComponent(jKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(18, 18, 18))
                         .addGroup(jPanel2Layout.createSequentialGroup()
                              .addGap(18, 18, 18)
                              .addComponent(jButton2)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel5)
                         .addComponent(jLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jidAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(8, 8, 8))
          );

          jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6});

          jTabbedPane2.addTab("Danh Sach Sinh Vien", jPanel2);

          jPanel3.addComponentListener(new java.awt.event.ComponentAdapter() {
               public void componentShown(java.awt.event.ComponentEvent evt) {
                    jPanel3ComponentShown(evt);
               }
          });

          jtbHocPhi.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null}
               },
               new String [] {
                    "IDSV", "Khóa", "Năm Học", "Tiền Phải Nộp", "Tiền Đã Nộp", "Action"
               }
          ));
          jtbHocPhi.setRowHeight(40);
          jScrollPane3.setViewportView(jtbHocPhi);

          javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
          jPanel3.setLayout(jPanel3Layout);
          jPanel3Layout.setHorizontalGroup(
               jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
          );
          jPanel3Layout.setVerticalGroup(
               jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
          );

          jTabbedPane2.addTab("Danh sách chi tiết", jPanel3);

          jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
               public void componentShown(java.awt.event.ComponentEvent evt) {
                    jTabbedPane1ComponentShown(evt);
               }
          });

          jPanel7.addComponentListener(new java.awt.event.ComponentAdapter() {
               public void componentShown(java.awt.event.ComponentEvent evt) {
                    jPanel7ComponentShown(evt);
               }
          });

          jtbTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
               },
               new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
               }
          ));
          jtbTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jtbTaiKhoanMouseClicked(evt);
               }
          });
          jScrollPane1.setViewportView(jtbTaiKhoan);

          javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
          jPanel7.setLayout(jPanel7Layout);
          jPanel7Layout.setHorizontalGroup(
               jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
          );
          jPanel7Layout.setVerticalGroup(
               jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
          );

          jTabbedPane1.addTab("TK", jPanel7);

          jPanel8.addComponentListener(new java.awt.event.ComponentAdapter() {
               public void componentShown(java.awt.event.ComponentEvent evt) {
                    jPanel8ComponentShown(evt);
               }
          });

          jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Ke Toan", "Sinh Vien" }));
          jComboBox1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jComboBox1ActionPerformed(evt);
               }
          });

          idsv.setText("ID Sinh Viên");

          ten.setText("Tên");

          cn.setText("Chuyên Ngành");

          lh.setText("Lớp Học ");

          kh.setText("Khóa Học");

          jLabel7.setText("id Account");

          username.setText("username");

          pass.setText("password");

          jLabel10.setText("Học Phí");

          namhoc.setText("Năm Học");

          tien.setText("Tiền Phải Đóng");

          jButton3.setText("Thêm");
          jButton3.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
               }
          });

          jButton4.setText("Thêm Học Phí");
          jButton4.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton4ActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
          jPanel8.setLayout(jPanel8Layout);
          jPanel8Layout.setHorizontalGroup(
               jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                              .addGap(47, 47, 47)
                              .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                              .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(idsv, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(cn)
                                   .addComponent(lh, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(kh, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(30, 30, 30)
                              .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jidsv, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jten, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jcn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jlh, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jk, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(jac, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addGroup(jPanel8Layout.createSequentialGroup()
                                                  .addComponent(jusername, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addGap(66, 66, 66)
                                                  .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                             .addComponent(jpass, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                   .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addGroup(jPanel8Layout.createSequentialGroup()
                                                  .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                       .addComponent(tien, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(namhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                  .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                       .addComponent(jtien, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(jnamhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                  .addGap(40, 40, 40)
                                                  .addComponent(jButton4))
                                             .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(124, 124, 124)))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          jPanel8Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cn, idsv, jLabel7, kh, lh, namhoc, pass, ten, tien, username});

          jPanel8Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jac, jcn, jidsv, jk, jlh, jnamhoc, jpass, jten, jtien, jusername});

          jPanel8Layout.setVerticalGroup(
               jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel8Layout.createSequentialGroup()
                              .addComponent(jidsv, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(38, 38, 38)
                              .addComponent(jten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(27, 27, 27)
                              .addComponent(jcn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(28, 28, 28)
                              .addComponent(jlh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(28, 28, 28)
                              .addComponent(jk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(jPanel8Layout.createSequentialGroup()
                              .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(145, 145, 145)
                                        .addComponent(cn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(lh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addGroup(jPanel8Layout.createSequentialGroup()
                                                  .addComponent(idsv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addGap(38, 38, 38)
                                                  .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                             .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                                       .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jac, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                       .addGap(38, 38, 38)
                                                       .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(username)
                                                            .addComponent(jusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                       .addGap(27, 27, 27)
                                                       .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(pass)
                                                            .addComponent(jpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                  .addGroup(jPanel8Layout.createSequentialGroup()
                                                       .addGap(82, 82, 82)
                                                       .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                             .addComponent(kh, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(namhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(jnamhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(tien))
                                   .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(jtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(80, 80, 80))
          );

          jPanel8Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cn, idsv, jLabel7, kh, lh, namhoc, pass, ten, tien, username});

          jPanel8Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jac, jcn, jidsv, jk, jlh, jnamhoc, jpass, jten, jtien, jusername});

          jTabbedPane1.addTab("Thêm", jPanel8);

          jTabbedPane2.addTab("Tài Khoản", jTabbedPane1);

          jPanel4.addComponentListener(new java.awt.event.ComponentAdapter() {
               public void componentShown(java.awt.event.ComponentEvent evt) {
                    jPanel4ComponentShown(evt);
               }
          });

          jjname.setText("username");

          jjcn.setText("Chuyen nganh");

          jjlop.setText("Lop");

          jjid.setText("1");

          jtbPrivate.setAutoCreateRowSorter(true);
          jtbPrivate.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {

               },
               new String [] {
                    "Năm Học ", "Phải Đóng", "Đã Đóng", "Action"
               }
          ) {
               Class[] types = new Class [] {
                    java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
               };
               boolean[] canEdit = new boolean [] {
                    false, false, false, true
               };

               public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
               }

               public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
               }
          });
          jtbPrivate.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jtbPrivateMouseClicked(evt);
               }
          });
          jScrollPane4.setViewportView(jtbPrivate);

          jLabel8.setText("          Họ và Tên:");

          jLabel9.setText("Chuyên Ngành :");

          jLabel11.setText("         Lớp:");

          jLabel12.setText("               Mã SV:");

          thanhtoan.setText("0");

          jLabel13.setText(" Thanh Toán:");

          jButton6.setText("Nộp");
          jButton6.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton6ActionPerformed(evt);
               }
          });

          jLabel14.setText("     Phải Đóng:");

          jLabel15.setBackground(new java.awt.Color(0, 204, 0));
          jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
          jLabel15.setForeground(new java.awt.Color(0, 204, 51));
          jLabel15.setText("jLabel15");

          jLabel16.setText("           Đã Đóng:");

          jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
          jLabel17.setForeground(new java.awt.Color(0, 204, 51));
          jLabel17.setText("jLabel17");

          javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
          jPanel4.setLayout(jPanel4Layout);
          jPanel4Layout.setHorizontalGroup(
               jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel4Layout.createSequentialGroup()
                                   .addGap(56, 56, 56)
                                   .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                   .addComponent(thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                   .addGap(107, 107, 107)
                                   .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                         .addGroup(jPanel4Layout.createSequentialGroup()
                              .addGap(56, 56, 56)
                              .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                             .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(jjname, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(jjid, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                             .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(jjcn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(jjlop, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)))))
                    .addGap(0, 82, Short.MAX_VALUE))
               .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(98, 98, 98)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(65, 65, 65)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel12, jLabel8});

          jPanel4Layout.setVerticalGroup(
               jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(76, 76, 76)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel4Layout.createSequentialGroup()
                              .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addContainerGap())
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                              .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jjid, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel12))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jjname, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jjcn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jjlop, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(30, 30, 30)
                              .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(67, 67, 67))))
               .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
          );

          jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel12, jLabel8});

          jTabbedPane2.addTab("Thanh Toán", jPanel4);

          jPanel5.addComponentListener(new java.awt.event.ComponentAdapter() {
               public void componentShown(java.awt.event.ComponentEvent evt) {
                    jPanel5ComponentShown(evt);
               }
          });

          javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
          jPanel5.setLayout(jPanel5Layout);
          jPanel5Layout.setHorizontalGroup(
               jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 875, Short.MAX_VALUE)
          );
          jPanel5Layout.setVerticalGroup(
               jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 579, Short.MAX_VALUE)
          );

          jTabbedPane2.addTab("Log Out", jPanel5);

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1008, javax.swing.GroupLayout.PREFERRED_SIZE)
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
          );

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
          // TODO add your handling code here:
          setdatatable();
          jidAccount.setVisible(false);

     }//GEN-LAST:event_jPanel2ComponentShown


     private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
          // TODO add your handling code here:
          int i = jTable1.getSelectedRow();
          TableModel model = jTable1.getModel();
          jidSV.setText(model.getValueAt(i, 0).toString());
          jidAccount.setText(model.getValueAt(i, 1).toString());
          jname.setText(model.getValueAt(i, 2).toString());
          jChuyenNganh.setText(model.getValueAt(i, 3).toString());
          jLopHoc.setText(model.getValueAt(i, 4).toString());
          jKhoa.setText(model.getValueAt(i, 5).toString());
     }//GEN-LAST:event_jTable1MouseClicked

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          // TODO add your handling code here:
          int id = Integer.parseInt(jidSV.getText());
          String name = jname.getText();
          String ChuyenNganh = jChuyenNganh.getText();
          String LopHoc = jLopHoc.getText();
          int khoa = Integer.parseInt(jKhoa.getText());

          String sql = " update SinhVien set idSV='" + id + "',name='" + name + "',ChuyenNganh='" + ChuyenNganh + "',LopHoc='" + LopHoc + "',KhoaHoc='" + khoa + "' where idSV='" + id + "' ";
          executeQuery(sql, "Update");
          setdatatable();
     }//GEN-LAST:event_jButton1ActionPerformed

     private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          // TODO add your handling code here:
          int id = Integer.parseInt(jidSV.getText());
          int idAccount = Integer.parseInt(jidAccount.getText());
          String sql = " delete from SinhVien where idSV='" + id + "' ";
          String sqlAC = "delete from account where idAccount='" + idAccount + "' ";
          String sqlHP = "delete from NopHocPhi where idSV='" + id + "' ";
          executeQuery(sqlHP, "HP");
          executeQuery(sql, "Delete");
          executeQuery(sqlAC, "aa");

          setdatatable();
          setdataTK();
     }//GEN-LAST:event_jButton2ActionPerformed

     private void jPanel7ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel7ComponentShown
          // TODO add your handling code here:
//          setdataTK();
     }//GEN-LAST:event_jPanel7ComponentShown


     private void jPanel3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel3ComponentShown
          // TODO add your handling code here:
          setdataHP();


     }//GEN-LAST:event_jPanel3ComponentShown

     private void jPanel8ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel8ComponentShown

          String item = (String) jComboBox1.getSelectedItem();
          if ("Admin".equals(item) || "Ke Toan".equals(item)) {
               SelectAdmin();
          }
     }//GEN-LAST:event_jPanel8ComponentShown

     private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

          String item = (String) jComboBox1.getSelectedItem();
          if ("Admin".equals(item) || "Ke Toan".equals(item)) {
               SelectAdmin();
          } else if ("Sinh Vien".equals(item)) {
               SelectSV();
          }
     }//GEN-LAST:event_jComboBox1ActionPerformed

     private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          // TODO add your handling code here:
          String item = (String) jComboBox1.getSelectedItem();
          if ("Sinh Vien".equals(item)) {
               int idsv = Integer.parseInt(jidsv.getText());
               int idac = Integer.parseInt(jac.getText());
               String ten = jten.getText();
               String chuyennganh = jcn.getText();
               String lophoc = jlh.getText();
               int khoahoc = Integer.parseInt(jk.getText());

               String sqlAC = "insert into account values('" + idac + "','" + ten + "','" + 1 + "','" + 0 + "')";
               String sqlSV = "insert into SinhVien values('" + idsv + "','" + idac + "','" + ten + "','" + chuyennganh + "','" + lophoc + "','" + khoahoc + "','" + 0 + "')";

               executeQuery(sqlAC, "account");
               executeQuery(sqlSV, "SinhVien");

          }
     }//GEN-LAST:event_jButton3ActionPerformed

     private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          // TODO add your handling code here:
          int idsv = Integer.parseInt(jidsv.getText());
          int khoahoc = Integer.parseInt(jk.getText());
          String namhoc = jnamhoc.getText();
          int tien = Integer.parseInt(jtien.getText());
          String sql = "insert into NopHocPhi values('" + idsv + "','" + khoahoc + "','" + namhoc + "','" + tien + "','" + 0 + "','" + 0 + "')";
          executeQuery(sql, "tien");
     }//GEN-LAST:event_jButton4ActionPerformed

     private void jtbTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbTaiKhoanMouseClicked
          // TODO add your handling code here:
          int i = jtbTaiKhoan.getSelectedRow();
          TableModel model = jtbTaiKhoan.getModel();
          account ac = new account();
          ac.setIdAccount(Integer.parseInt(model.getValueAt(i, 0).toString()));
          ac.setUsername(model.getValueAt(i, 1).toString());
          ac.setPassword(model.getValueAt(i, 2).toString());
          ac.setRole(Integer.parseInt(model.getValueAt(i, 3).toString()));
          editTK e = null;
          try {
               e = new editTK(ac);
          } catch (SQLException ex) {
               Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
          }
          e.setVisible(true);
          e.pack();
          e.setLocationRelativeTo(null);
          e.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
          e.addWindowListener(new WindowAdapter() {
               @Override
               public void windowClosed(WindowEvent e) {
                    setdataTK();
               }
          });

     }//GEN-LAST:event_jtbTaiKhoanMouseClicked

     private void jPanel4ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel4ComponentShown
          // TODO add your handling code here:
          setdataPrivate();
          TableModel model = jtbPrivate.getModel();
          for (int i = 0; i < model.getRowCount(); i++) {
               model.setValueAt(false, i, 3);
          }
     }//GEN-LAST:event_jPanel4ComponentShown

     private void jPanel5ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel5ComponentShown
          // TODO add your handling code here:
          this.dispose();
          SignIn sign = null;
          try {
               sign = new SignIn();
          } catch (SQLException ex) {
               Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
          }
          sign.setVisible(true);
     }//GEN-LAST:event_jPanel5ComponentShown
     public int sum = 0;
     public ArrayList<HocPhi> list = new ArrayList<>();

     private void jtbPrivateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbPrivateMouseClicked
          // TODO add your handling code here:

          int i = jtbPrivate.getSelectedRow();
          TableModel model = jtbPrivate.getModel();
          if ("true".equals(model.getValueAt(i, 3).toString()) && jtbPrivate.isColumnSelected(3)) {
               System.out.println(i);
               int item = Integer.parseInt(model.getValueAt(i, 1).toString()) - Integer.parseInt(model.getValueAt(i, 2).toString());

               sum = sum + item;
               thanhtoan.setText(String.valueOf(sum));

          } else if ("false".equals(model.getValueAt(i, 3).toString()) && jtbPrivate.isColumnSelected(3)) {
               int item = Integer.parseInt(model.getValueAt(i, 1).toString()) - Integer.parseInt(model.getValueAt(i, 2).toString());
               sum = sum - item;
               thanhtoan.setText(String.valueOf(sum));

          }

     }//GEN-LAST:event_jtbPrivateMouseClicked

     private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
          // TODO add your handling code here:
          for (int i = 0; i < jtbPrivate.getRowCount(); i++) {
               if ("true".equals(jtbPrivate.getValueAt(i, 3).toString())) {
                    HocPhi hp = new HocPhi();
                    hp.setIdSV(Integer.parseInt(jjid.getText()));
                    hp.setNamHoc(jtbPrivate.getValueAt(i, 0).toString());
                    hp.setTienPhaiNop(Integer.parseInt(jtbPrivate.getValueAt(i, 1).toString()));
                    hp.setTienDaNop(Integer.parseInt(jtbPrivate.getValueAt(i, 2).toString()));
                    list.add(hp);
               }
          }
          HoaDon hd = null;
          try {
               hd = new HoaDon(list);
          } catch (SQLException ex) {
               Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
          }
          hd.setVisible(true);
          hd.pack();
          hd.setLocationRelativeTo(null);
          hd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
          hd.addWindowListener(new WindowAdapter() {
               @Override
               public void windowClosed(WindowEvent e) {
                    setdataPrivate();
                    if (jtbPrivate.getRowCount() == 0) {
                         thanhtoan.setText("0");
                    }
               }
          });


     }//GEN-LAST:event_jButton6ActionPerformed

     private void jTabbedPane1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentShown
          // TODO add your handling code here:
          setdataTK();
     }//GEN-LAST:event_jTabbedPane1ComponentShown

     public void setdatatable() {
          DefaultTableModel model = new DefaultTableModel();
          model.addColumn("idSV");
          model.addColumn("idAcount");
          model.addColumn("ho va ten");
          model.addColumn("Chuyen Nganh");
          model.addColumn("Lop Hoc");
          model.addColumn("Khoa Hoc");
          model.addColumn("status");
          ArrayList<SinhVien> list = new ArrayList<>();
          controller cr = new controller();
          try {
               list = cr.setdata();
               System.out.println(list);
               for (int i = 0; i < list.size(); i++) {
                    String check = "";
                    SinhVien sv = (SinhVien) list.get(i);
                    if (sv.getStatus() == 1) {
                         check = "Đã Nộp Đủ";
                    } else {
                         check = "Chưa Đủ";
                    }
                    Object[] rowdata = {sv.getIdSV(), sv.getIdAccount(), sv.getName(), sv.getChuyenNganh(), sv.getLopHoc(), sv.getKhoaHoc(), check};
                    model.addRow(rowdata);
               }
          } catch (SQLException ex) {
               Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
          }
          jTable1.setModel(model);
          rowSoft = new TableRowSorter<>(jTable1.getModel());
          jTable1.setRowSorter(rowSoft);

          jsearch.getDocument().addDocumentListener(new DocumentListener() {
               @Override
               public void insertUpdate(DocumentEvent e) {
                    String text = jsearch.getText();
                    if (text.trim().length() == 0) {
                         rowSoft.setRowFilter(null);
                    } else {
                         rowSoft.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                    }
               }

               @Override
               public void removeUpdate(DocumentEvent e) {
                    String text = jsearch.getText();
                    if (text.trim().length() == 0) {
                         rowSoft.setRowFilter(null);
                    } else {
                         rowSoft.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                    }
               }

               @Override
               public void changedUpdate(DocumentEvent e) {
               }

          });
     }

     public void setdataTK() {
          DefaultTableModel model = new DefaultTableModel();
          model.addColumn("IDAccount");
          model.addColumn("username");
          model.addColumn("password");
          model.addColumn("Role");
          ArrayList<account> list = new ArrayList<>();
          controller cr = new controller();

          try {
               list = cr.setdataAC();
               System.out.println(list);
               for (int i = 0; i < list.size(); i++) {
                    String quyen = "";
                    account ac = (account) list.get(i);
                    if (ac.getRole() == 1) {
                         quyen = "Admin";
                    } else if (ac.getRole() == 0) {
                         quyen = "Sinh Viên";
                    }
                    Object[] rowdata = {ac.getIdAccount(), ac.getUsername(), ac.getPassword(), quyen};
                    model.addRow(rowdata);
               }
          } catch (SQLException ex) {
               Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
          }
          jtbTaiKhoan.setModel(model);
     }

     public void setdataHP() {

          DefaultTableModel model = new DefaultTableModel();
          model.addColumn("IDSV");
          model.addColumn("Khóa");
          model.addColumn("Năm Học");
          model.addColumn("Tiền Phải Nộp");
          model.addColumn("Tiền Đã Nộp");
          model.addColumn("action");
          ArrayList<HocPhi> list = new ArrayList<>();
          controller cr = new controller();
          try {
               list = cr.setdataHP();
               System.out.println(list);
               for (int i = 0; i < list.size(); i++) {
                    HocPhi hp = (HocPhi) list.get(i);
                    Object[] rowdata = {hp.getIdSV(), hp.getKhoaHoc(), hp.getNamHoc(), hp.getTienPhaiNop(), hp.getTienDaNop()};
                    model.addRow(rowdata);
               }
          } catch (SQLException ex) {
               Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
          }
          jtbHocPhi.setModel(model);

          TableActionEvent event;
          event = new TableActionEvent() {
               @Override
               public void onEdit(int row) {
                    HocPhi hocphi = new HocPhi();
                    int i = jtbHocPhi.getSelectedRow();
                    TableModel model = jtbHocPhi.getModel();
                    hocphi.setIdSV(Integer.parseInt(model.getValueAt(i, 0).toString()));
                    hocphi.setKhoaHoc(Integer.parseInt(model.getValueAt(i, 1).toString()));
                    hocphi.setNamHoc(model.getValueAt(i, 2).toString());
                    hocphi.setTienPhaiNop(Integer.parseInt(model.getValueAt(i, 3).toString()));
                    hocphi.setTienDaNop(Integer.parseInt(model.getValueAt(i, 4).toString()));
                    edit e = null;
                    try {
                         e = new edit(hocphi);
                    } catch (SQLException ex) {
                         Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    e.setVisible(true);
                    e.pack();
                    e.setLocationRelativeTo(null);
                    e.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    e.addWindowListener(new WindowAdapter() {
                         @Override
                         public void windowClosed(WindowEvent e) {
                              setdataHP();
                         }
                    });

               }

               @Override
               public void onDelete(int row) {
                    HocPhi hocphi = new HocPhi();
                    int i = jtbHocPhi.getSelectedRow();
                    TableModel model = jtbHocPhi.getModel();
                    hocphi.setIdSV(Integer.parseInt(model.getValueAt(i, 0).toString()));
                    hocphi.setKhoaHoc(Integer.parseInt(model.getValueAt(i, 1).toString()));
                    hocphi.setNamHoc(model.getValueAt(i, 2).toString());
                    hocphi.setTienPhaiNop(Integer.parseInt(model.getValueAt(i, 3).toString()));
                    hocphi.setTienDaNop(Integer.parseInt(model.getValueAt(i, 4).toString()));
                    int id = hocphi.getIdSV();
                    String namhoc = hocphi.getNamHoc();
                    String sql = "delete from NopHocPhi where idSV='" + id + "'and NamHoc='" + namhoc + "' ";
                    executeQuery(sql, "delete");
                    setdataHP();
               }

               @Override
               public void onView(int row) {
                    System.out.println("View row : " + row);
               }
          };
          jtbHocPhi.getColumnModel().getColumn(5).setCellRenderer(new TableActionCellRender());
          jtbHocPhi.getColumnModel().getColumn(5).setCellEditor(new TableActionCellEditor(event));
     }

     public void setdataPrivate() {
          int id = Integer.parseInt(jjid.getText());
          thanhtoan.setText("0");
          DefaultTableModel model = new DefaultTableModel() {
               @Override
               public Class getColumnClass(int column) {
                    if (column == 3) {
                         return Boolean.class;
                    } else {
                         return Object.class;
                    }
               }
          };
          model.addColumn("Nam Hoc");
          model.addColumn("Phai Dong");
          model.addColumn("da dong");
          model.addColumn("Thanh Toann");
          ArrayList<HocPhi> list = new ArrayList<>();

          controller cr = new controller();
          try {
               list = cr.SetdataPrivate(id);
               System.out.println(list);
               for (int i = 0; i < list.size(); i++) {
                    HocPhi hp = (HocPhi) list.get(i);
                    Object[] rowdata = {hp.getNamHoc(), hp.getTienPhaiNop(), hp.getTienDaNop()};
                    model.addRow(rowdata);
               }
          } catch (SQLException ex) {
               Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
          }
          jtbPrivate.setModel(model);
          checkStatus(id);

     }

     public void checkStatus(int id) {
          try {
               int check = 1;
               int sumphaidong = 0;
               int sumdadong = 0;
               String sql = "select * from NopHocPhi where idSV='" + id + "' ";
               PreparedStatement ps = con.prepareCall(sql);
               ResultSet rs = ps.executeQuery();
               while (rs.next()) {
                    sumphaidong += rs.getInt("TienPhaiNop");
                    sumdadong += rs.getInt("TienDaNop");
                    if (rs.getInt("status") == 0) {
                         check = 0;
                    }
               }
               jLabel15.setText(String.valueOf(sumphaidong));
               jLabel17.setText(String.valueOf(sumdadong));
               if (check == 1) {
                    String sql1 = "update SinhVien set  status='" + check + "'where idSV='" + id + "' ";
                    executeQuery(sql1, "update");
               }
          } catch (SQLException e) {
               e.printStackTrace();
          }
     }

     public void executeQuery(String query, String message) {
          Statement st;
          try {
               st = con.createStatement();
               st.executeUpdate(query);

          } catch (SQLException ex) {
               ex.printStackTrace();
          }
     }

     public void SelectAdmin() {
          idsv.setVisible(false);
          ten.setVisible(false);
          cn.setVisible(false);
          lh.setVisible(false);
          kh.setVisible(false);
          jidsv.setVisible(false);
          jten.setVisible(false);
          jcn.setVisible(false);
          jlh.setVisible(false);
          jk.setVisible(false);
          jLabel10.setVisible(false);
          jSeparator2.setVisible(false);
          namhoc.setVisible(false);
          tien.setVisible(false);
          jnamhoc.setVisible(false);
          jtien.setVisible(false);
          jButton4.setVisible(false);

          username.setVisible(true);
          pass.setVisible(true);
          jusername.setVisible(true);
          jpass.setVisible(true);
     }

     public void SelectSV() {
          username.setVisible(false);
          pass.setVisible(false);
          jusername.setVisible(false);
          jpass.setVisible(false);

          idsv.setVisible(true);
          ten.setVisible(true);
          cn.setVisible(true);
          lh.setVisible(true);
          kh.setVisible(true);
          jidsv.setVisible(true);
          jten.setVisible(true);
          jcn.setVisible(true);
          jlh.setVisible(true);
          jk.setVisible(true);
          jLabel10.setVisible(true);
          jSeparator2.setVisible(true);
          namhoc.setVisible(true);
          tien.setVisible(true);
          jnamhoc.setVisible(true);
          jtien.setVisible(true);
          jButton4.setVisible(true);
     }

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(() -> {
               try {
                    new NewJFrame().setVisible(true);
               } catch (SQLException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JLabel cn;
     private javax.swing.JLabel idsv;
     private javax.swing.JButton jButton1;
     private javax.swing.JButton jButton2;
     private javax.swing.JButton jButton3;
     private javax.swing.JButton jButton4;
     private javax.swing.JButton jButton6;
     private javax.swing.JTextField jChuyenNganh;
     private javax.swing.JComboBox<String> jComboBox1;
     private javax.swing.JTextField jKhoa;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel10;
     private javax.swing.JLabel jLabel11;
     private javax.swing.JLabel jLabel12;
     private javax.swing.JLabel jLabel13;
     private javax.swing.JLabel jLabel14;
     private javax.swing.JLabel jLabel15;
     private javax.swing.JLabel jLabel16;
     private javax.swing.JLabel jLabel17;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JLabel jLabel8;
     private javax.swing.JLabel jLabel9;
     private javax.swing.JTextField jLopHoc;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JPanel jPanel3;
     private javax.swing.JPanel jPanel4;
     private javax.swing.JPanel jPanel5;
     private javax.swing.JPanel jPanel7;
     private javax.swing.JPanel jPanel8;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JScrollPane jScrollPane2;
     private javax.swing.JScrollPane jScrollPane3;
     private javax.swing.JScrollPane jScrollPane4;
     private javax.swing.JSeparator jSeparator2;
     private javax.swing.JTabbedPane jTabbedPane1;
     private javax.swing.JTabbedPane jTabbedPane2;
     private javax.swing.JTable jTable1;
     private javax.swing.JTextField jac;
     private javax.swing.JTextField jcn;
     private javax.swing.JTextField jidAccount;
     private javax.swing.JTextField jidSV;
     private javax.swing.JTextField jidsv;
     private javax.swing.JLabel jjcn;
     private javax.swing.JLabel jjid;
     private javax.swing.JLabel jjlop;
     private javax.swing.JLabel jjname;
     private javax.swing.JTextField jk;
     private javax.swing.JTextField jlh;
     private javax.swing.JTextField jname;
     private javax.swing.JTextField jnamhoc;
     private javax.swing.JTextField jpass;
     private javax.swing.JTextField jsearch;
     private javax.swing.JTable jtbHocPhi;
     private javax.swing.JTable jtbPrivate;
     private javax.swing.JTable jtbTaiKhoan;
     private javax.swing.JTextField jten;
     private javax.swing.JTextField jtien;
     private javax.swing.JTextField jusername;
     private javax.swing.JLabel kh;
     private javax.swing.JLabel lh;
     private javax.swing.JLabel namhoc;
     private javax.swing.JLabel pass;
     private javax.swing.JLabel ten;
     private javax.swing.JLabel thanhtoan;
     private javax.swing.JLabel tien;
     private javax.swing.JLabel username;
     // End of variables declaration//GEN-END:variables

}
